# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  mysite:
    site_hosts:
      - canonical: mysite.dev #in dev environment this is localhost address
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: grayson.bartlet@shaw.ca
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
